### ISSUE TITLE
Scroll issue with jQuery 

### ISSUE THREAD

**Issue by sojonatgithub** [hmongouachon/NodeCursor#3]
Using jQuery when I scroll-down the NodeCursor will not in the position of mouse-pointer.

[https://codepen.io/hmongouachon/pen/Ygwjrj](https://codepen.io/hmongouachon/pen/Ygwjrj)

in this pen, please remove the `overflow: hidden;` from `body, html` in CSS and add some text in HTML for scrollable output to see the issue.

**Comment by egemenerd** [comment]
#4

**Comment by egemenerd** [comment]
Replace "pageX" with "clientX" and replace "pageY" with "clientY". It will work properly.

https://github.com/egemenerd/NodeCursor/blob/master/src/nodecursor-jquery.js
